# Docker compose for production ready
version: "3.9"

services:
    postgres-server:
        image: postgres:14-alpine
        environment:
            - POSTGRES_PASSWORD=postgres
        ports:
            - "54321:5432"
    redis-server:
        image: redis:latest
    nginx:
        restart: always
        image: putraawali/fibonachi-nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
        depends_on:
            - api
            - client
        ports:
            - "8080:80" # We will access our project from port 8080
    api:
        image: putraawali/fibonachi-server
        build:
            context: ./server
            dockerfile: Dockerfile
        environment:
            - REDIS_HOST=redis-server
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres-server
            - PGDATABASE=postgres
            - PGPASSWORD=postgres
            - PGPORT=5432
        depends_on:
            - postgres-server
            - redis-server
    worker:
        image: putraawali/fibonachi-worker
        build:
            context: ./worker
            dockerfile: Dockerfile
        environment:
            - REDIS_HOST=redis-server
            - REDIS_PORT=6379
        depends_on:
            - redis-server
    client:
        image: putraawali/fibonachi-client
        build:
            context: ./client
            dockerfile: Dockerfile
        depends_on:
            - api
