apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: database-persistent-volume-claim
spec:
    accessModes:
        - ReadWriteOnce # can be used by a single node at a time
        # - ReadOnlyMany can be used by multiple nodes only for read
        # - ReadWriteMany can be used by multiple nodes to do read and write
    resources:
        requests:
            storage: 2Gi
# Note to remember:
# Persistent Volume Claims is NOT an actual instance of storage. PVC is something that we're gonna attach the the pod config that we requested to K8s.
